name: SubspaceExp
dependencies:
  - python>=3.5
  - pip>=19
  - matplotlib
  - notebook
  - ipywidgets
  - pip:
      - qiskit
      - pandas
      - statsmodels
      - sympy
      - multiprocessing
